### ISSUE TITLE
Can we add markdown cells?

### ISSUE THREAD

**Issue by JohnReid** [untitled-ai/jupyter_ascending.vim#10]
Is it possible to add markdown cells to the notebook via the sync?

**Comment by pi1Mg** [comment]
Not sure if I understood you correctly, but maybe what need is to write something like this:

> # %%  [markdown]
> """
> # Your Markdown Heading
> ---
> """

**Comment by IliaOzhmegov** [comment]
Hi @Eloitor there is a numerous amount of plugins for that! I'm afraid that is not something that is supposed to be covered by `jupyter_ascending.vim` plugin. It only sends two commands `sync` and `execute`. Although, I understand why you are addressing it here. I can only advise to allow markdown syntax highlighting in python files.

**Comment by zplizzi** [comment]
Yeah, i'm not sure that existing markdown plugins would correctly handle the case of markdown embedded in a py:percent formatted python file, but I agree that that formatting is out of scope for this plugin.
